

export const ALL_INFOS_REQUEST = 'ALL_INFOS_REQUEST';
export const ALL_INFOS_SUCCESS = 'ALL_INFOS_SUCCESS';
export const ALL_INFOS_FAIL = 'ALL_INFOS_FAIL';

export const PUBLISH_INFO_REQUEST = 'PUBLISH_INFO_REQUEST';
export const PUBLISH_INFO_SUCCESS = 'PUBLISH_INFO_SUCCESS';
export const PUBLISH_INFO_FAIL = 'PUBLISH_INFO_FAIL';


 export const CLEAR_ERRORS = 'CLEAR_ERRORS';

 