export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const INCREASE_QUANTITY = 'INCREASE_QUANTITY';
export const DECREASE_QUANTITY = 'DECREASE_QUANTITY';
// export const PROCCEED_TO_CHECKOUT = 'PROCCEED_TO_CHECKOUT';


export const CART_RESET = 'CART_RESET';
export const ADD_CART_FAIL = 'ADD_CART_FAIL';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';
