export const PROCCEED_TO_CHECKOUT_SUCCESS = 'PROCCEED_TO_CHECKOUT_SUCCESS';
export const PROCCEED_TO_CHECKOUT_FAIL = 'PROCCEED_TO_CHECKOUT_FAIL';

export const ORDER_SUMMARY_SUCCESS = 'ORDER_SUMMARY_SUCCESS';
export const ORDER_SUMMARY_FAIL = 'ORDER_SUMMARY_FAIL';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';


